DefaultContentLanguage = "en"
baseurl = "https://blog.hyperdata.ltd/"
hasCJKLanguage = true
languageCode = "zh-cn"
metaDataFormat = "yaml"
pygmentCodeFences = true
pygmentsUseClasses = false
theme = "beautifulhugo"
title = " Ai-SCA （Sping Cloud Admin）参考文档"
[Author]
email = "ffanwx@asiainfo.com"
github = "fanbbs"
name = "CUC TC-PPAD"
website = "https://blog.hyperdata.ltd"
[Params]
commit = false
dateFormat = "January 2, 2006"
description = "Sring Cloud admin|SCA|Cloud Native|Mico Service"
errorpage = "https://res.cloudinary.com/jimmysong/image/upload/images/404-not-found-cat.png"
favicon = "https://raw.githubusercontent.com/fanbbs/fanbbs.github.io/master/images/favicon.ico"
hello = "Hi,this is Ai-SCA(Srping Cloud Admin)  Blog"
logo = "https://raw.githubusercontent.com/fanbbs/fanbbs.github.io/master/images/favicon.ico"
rss = true
subtitle = "Let's create bright future together!"
[[Params.bigimg]]
desc = "KEUC - China Kubernetes End User Conference 2017"
src = "https://res.cloudinary.com/jimmysong/image/upload/banners/keuc-cncf1.jpg"
[[Params.bigimg]]
desc = "Kubernetes Beijing fans meetup - Aug 28,2017"
src = "https://res.cloudinary.com/jimmysong/image/upload/banners/kubernetes-meetup-china-201708216.jpg"
[[Params.bigimg]]
desc = "Democratizing the Cloud Computing for every one"
src = "https://res.cloudinary.com/jimmysong/image/upload/banners/cloud-computing1.jpg"
[[Params.bigimg]]
desc = "Insight throught the Great Wall to the world"
src = "https://res.cloudinary.com/jimmysong/image/upload/banners/great-wall-0111.jpg"
[[Params.bigimg]]
desc = "Using Big Data to make business decision"
src = "https://res.cloudinary.com/jimmysong/image/upload/banners/big-data-11.jpg"
[[menu.main]]
identifier = "About"
name = "关 于"
url = "About"
weight = 16
[[menu.main]]
name = "Istio service mesh"
parent = "Docs"
url = "http://istio.doczh.cn"
weight = 14
[[menu.main]]
name = "Microservices"
parent = "Blog"
url = "Blog/microservices"
weight = 12
[[menu.main]]
name = "Hugo经验"
parent = "Docs"
url = "hugo-handbook"
weight = 11
[[menu.main]]
name = "k8s技巧"
parent = "Blog"
url = "categories/kubernetes"
weight = 3
[[menu.main]]
name = "Cloud Native"
parent = "DevOps"
url = "posts/cloud-native-go"
weight = 3
[[menu.main]]
name = "K8S Plus"
parent = "DevOps"
url = "posts/cloud-native-java"
weight = 2
[[menu.main]]
name = "Devops Stack"
parent = "DevOps"
url = "posts/devops stack"
weight = 1
[[menu.main]]
name = "PSO案例"
parent = "Projects"
url = "posts/pso"
weight = 9
[[menu.main]]
name = "R&D分享"
parent = "Projects"
url = "research"
weight = 5
[[menu.main]]
name = "微服务"
parent = "Projects"
url = "spark-on-k8s"
weight = 1
[[menu.main]]
identifier = "Projects"
name = "项 目"
weight = 13
[[menu.main]]
identifier = "DevOps"
name = "DevOps"
weight = 10
[[menu.main]]
name = "Docker技巧"
parent = "Docs"
url = "docker-handbook"
weight = 6
[[menu.main]]
name = "K8s手册"
parent = "Docs"
url = "kubernetes-handbook"
weight = 2
[[menu.main]]
identifier = "Docs"
name = "文 档"
weight = 7
[[menu.main]]
name = "Github"
parent = "Blog"
url = "Blog/github"
weight = 15
[[menu.main]]
name = "DC/OS"
parent = "Blog"
url = "Blog/dcos"
weight = 8
[[menu.main]]
identifier = "Blog"
name = "文 章"
weight = 4
